---
title: "Lab-04 Dynamic Graphics Solution(s)"
output: flexdashboard::flex_dashboard
runtime: shiny
---

```{r global, include = FALSE}

library(Lahman)
library(dplyr)
data(Teams)

ave.so <- Teams$SO / Teams$G
year <- Teams$yearID

ave.so.min <- min(ave.so, na.rm = TRUE)
ave.so.max <- max(ave.so, na.rm = TRUE)

league.ave <- tapply(X = ave.so, 
                     INDEX = as.factor(year), 
                     FUN = "mean", 
                     na.rm = TRUE)

league.year <- as.numeric(names(league.ave))


Teams$ave.so <- ave.so

```



Column {.sidebar}
-----------------------------------------------------------------------

Select a team to highlight on the graph.

```{r}


selectInput(
  
  
  inputId = "my_team",
  label = "Select a team:",
  choices = c("Choose a Team",
              "Cincinnati Reds",
              "Philadelphia Phillies",
              "Pittsburgh Pirates",
              "Oakland Athletics",
              "St. Louis Cardinals",
              "Chicago White Sox",
              "Detroit Tigers",
              "Cleveland Indians",
              "Boston Red Sox",
              "New York Yankees",
              "Chicago Cubs"),
  selected = "Chose a Team"
  
  )


```


**Author:** Muge Kosar

**Date:**  `r format(Sys.time(), '%B %d, %Y')`


Column
-----------------------------------------------------------------------

### Strikeouts on the Rise

```{r, fig.width=12,fig.height=8}

renderPlot({

index <- which(Teams$yearID <= 2012 & Teams$yearID >= 1900)

Teams <- Teams[index, ]
  
index <- which(year <= 2012 & year >= 1900)

ave.so <- ave.so[index]
year <- year[index]

index <- which(league.year <= 2012 
               & league.year >= 1900)

league.ave <- league.ave[index]
league.year <- league.year[index]

team.name <- input$my_team                  
dat.one.team <- filter(Teams, 
                       name == team.name)   

plot.new()

plot.window(xlim = c(1900, 2012), 
            ylim = c(ave.so.min, 
                     ave.so.max))
points(x = year, 
       y = ave.so,
       col = "gray85",
       pch = 16,
       cex = 0.75)
axis(side = 1,                      
     lwd = 2,                       
     hadj = -0.1,                   
     padj = -1,                     
     at = seq(from = 1900, 
              to = 2010, 
              by = 10))             
axis(side = 4,                     
     lwd = 0,                       
     las = 1,                       
     col.axis = "gray85",          
     at = seq(from = 0,             
              to = 9, 
              by = 1))

abline(h=1:9,
       lty="dashed", col="gray85", cex=1) 
mtext(text ="Strikeouts on the Rise",
      adj=0,
      family="serif",
      cex=1.7)
mtext(text = "There were more strikeouts in 2012 than any other time in major league history",
      adj=0,
      family="serif",
      cex=1.1,
      padj = 2)
text(x=1924, y=1.9,labels="League average\n 1924",font=2, cex=0.7)
text(x=1924, y=2.42,labels="2.7",font=2, cex=1.5,col="deepskyblue4")

points(x=1924,
       y=2.7,
       col="gray50",
       cex=1.5,
       lwd=0.5)

text(x=2012,y=8.3,labels="2012\n League average",font=2, cex=0.7)
text(x=2012, y=7.8,labels="7.5",font=2, cex=1.5,col="deepskyblue4")

points(x=2012,
       y=7.5,
       col="gray50",
       cex=1.5,
       lwd=0.5)

text(1917, 1.5,"U.S. enters\n World War I", pos=1, cex=0.7, col="gray80")

segments(x0=1917,
         x1=1917,
         y0=3.7,
         y1=1.3,
         col="gray80")

text(1946, 2.1,"Players return\n from  World War II", pos=1, cex=0.7, col="gray80")

segments(x0=1946,
         x1=1946,
         y0=4,
         y1=2,
         col="gray80")

text(1963, 3.2,"Strike zone enlarged\n from  1963-68", pos=1, cex=0.7, col="gray80")

segments(x0=1963,
         x1=1963,
         y0=5.9,
         y1=2.9,
         col="gray80")

text(1969, 8,"Pitching had become so dominant\n in the 1960s that the mound\n was lowered in 1969.", pos=3, cex=0.7, col="gray80")

segments(x0=1969,
         x1=1969,
         y0=8,
         y1=6,
         col="gray80")

text(1972, 2.1,"Designated hitter\n rule took effect", pos=1, cex=0.7, col="gray80")

segments(x0=1972,
         x1=1972,
         y0=5.1,
         y1=1.9,
         col="gray80")

text(2008, 4,"Mitchell report\n on steroids.", pos=1, cex=0.7, col="gray80")

segments(x0=2008,
         x1=2008,
         y0=7,
         y1=4,
         col="gray80")

mtext(text ="Strikeouts per game per team",
      adj=0,
      font=2,
      cex=0.9,
      padj = 8)


mtext(text ="(by batters)",
      adj=0.22,
      col="gray60",
      cex=0.9,
      padj = 8) 

lines(x=league.year,
      y=league.ave,
      type="l",
      col="deepskyblue4",
      lwd=1)

points(x=league.year,
      y=league.ave,
      col="deepskyblue4",
      cex=1,
      pch=16)

lines(x=dat.one.team$yearID,
      y=dat.one.team$ave.so,
      type="l",
      col="goldenrod1",
      lwd=1)

points(x=dat.one.team$yearID,
      y=dat.one.team$ave.so,
      pch=20,  cex=1.2, col="goldenrod1", type="b")

segments( x0=1900, y0=8.3, x1=1904, y1=8.3, col="goldenrod1", lwd = 1.5 )
points( x=c(1900,1904), y=c(8.3,8.3), col="goldenrod1", pch=20, cex=1.2 )
text ( x=1912, y=8.3, col="goldenrod1", labels=team.name, cex=0.8 )

segments( x0=1900, y0=8.6, x1=1904, y1=8.6, col="deepskyblue4", lwd = 1.5 )
points( x=c(1900,1904), y=c(8.6,8.6), col="deepskyblue4", pch=20, cex=1.2 )
text ( x=1912, y=8.6, col="deepskyblue4", labels="League average", cex=0.8 )


  
})

```

